name: ondc Deployment

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  ssh-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH Setup and Folder Creation
        run: |
          echo "${{ secrets.KEY }}" > ./key.pem
          chmod 600 ./key.pem
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          ssh -i ./key.pem ${{ secrets.USER }}@${{ secrets.HOST }} -T <<EOF
          if [ -d "retail-log-utility" ]; then
            echo "retail-log-utility folder exists, cleaning up"
            cd ./retail-log-utility && sudo docker-compose down && sudo rm -rf ./../retail-log-utility
          else
            echo "Creating retail-log-utility"
            sudo mkdir retail-log-utility 
          fi
          EOF

      - name: SCP to Copy Files to EC2 Server
        run: |
          sudo scp -i ./key.pem -r * ${{ secrets.USER }}@${{ secrets.HOST }}:/home/"${{ secrets.USER }}"/retail-log-utility

      - name: Ondc Deployment
        run: |
          ssh -o ServerAliveInterval=30 -o TCPKeepAlive=yes -T -i ./key.pem ${{ secrets.USER }}@${{ secrets.HOST }} <<EOF
          ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          cd ./retail-log-utility
          cp ~/.env ~/retail-log-utility/ 
          sudo docker-compose up -d --build
          EOF
